name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Verify GitHub Pages setup
        run: |
          echo "GitHub Pages is set to deploy from the main branch."
          ls -la
