# .github/workflows/patreon-sync.yml
name: Patreon Sync

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  sync-patreon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install node-fetch

      - name: Process pending codes
        env:
          PATREON_CLIENT_ID: ${{ secrets.PATREON_CLIENT_ID }}
          PATREON_CLIENT_SECRET: ${{ secrets.PATREON_CLIENT_SECRET }}
        run: |
          node .github/scripts/patreon-sync.js
