name: Ping Heroku Dyno

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping-dyno:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Heroku app
        run: |
          curl -s -o /dev/null https://mypetid-map-69b6f0c23e33.herokuapp.com/
          echo "Pinged Heroku app successfully"
