name: Update Location Data

on:
  issue_comment:
    types: [created]

jobs:
  update-location:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request == null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract lat/lon/timestamp from comment
        id: extract
        run: |
          echo '${{ github.event.comment.body }}' > comment.json
          LAT=$(jq -r '.lat' comment.json)
          LON=$(jq -r '.lon' comment.json)
          TIMESTAMP=$(jq -r '.timestamp' comment.json)
          if [[ "$LAT" == "null" || "$LON" == "null" || "$TIMESTAMP" == "null" ]]; then
            echo "Latitude, Longitude, or Timestamp not found in the comment."
            exit 1
          fi
          echo "LAT=$LAT" >> $GITHUB_ENV
          echo "LON=$LON" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Update locations.json
        run: |
          TIMESTAMP_DATE=$(date -d @$((TIMESTAMP)) +%Y-%m-%dT%H:%M:%SZ)
          NEW_LOCATION='{"_id": "'$(uuidgen)'", "dogId": "682774024ca6684a976c5f8e", "deviceName": "Tasker Device", "latitude": '$LAT', "longitude": '$LON', "timestamp": "'$TIMESTAMP_DATE'", "active": true}'
          if [ -f "data/locations.json" ]; then
            LOCATIONS=$(cat data/locations.json)
            if [ -z "$LOCATIONS" ] || ! echo "$LOCATIONS" | jq -e . >/dev/null 2>&1; then
              LOCATIONS='[]'
            fi
            UPDATED_LOCATIONS=$(echo "$LOCATIONS" | jq -c '. += ['"$NEW_LOCATION"']')
          else
            UPDATED_LOCATIONS='['"$NEW_LOCATION"']'
          fi
          echo "$UPDATED_LOCATIONS" > data/locations.json
          echo "Location data updated successfully."

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/locations.json
          git diff --cached --quiet || git commit -m "Update location to lat: $LAT, lon: $LON, timestamp: $TIMESTAMP"
          git push
